language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base
install:
  - "sudo pip install -r requirements.txt"
script:
  - "make test"
